import { RawMaterialRecord } from '../types';

export function getPharmaMasterDemoRecords(): RawMaterialRecord[] {
  const records: RawMaterialRecord[] = [];

  // ==========================================
  // 1. APIs (Active Pharmaceutical Ingredients)
  // ==========================================
  const apiItems = [
    // SPEC EXAMPLE 1: Anhydrous Polysaccharide (APS)
    {
      name: 'Anhydrous Polysaccharide',
      qc: 'QC-00125',
      date: '2026-01-12',
      cat: 'API',
      supplier: 'ABC Pharma Ingredients Ltd',
      batch: 'APS-26-014',
      mfg: 'BioPolymer ChemWorks',
      status: 'Approved',
      purity: '99.4%',
      spec: 'Ph. Eur / In-House 2026-01',
      storage: 'Store below 25°C in tight container',
      sampleQty: '250 g',
    },
    {
      name: 'Anhydrous Polysaccharide',
      qc: 'QC-00452',
      date: '2026-03-18',
      cat: 'API',
      supplier: 'ABC Pharma Ingredients Ltd',
      batch: 'APS-26-089',
      mfg: 'BioPolymer ChemWorks',
      status: 'Approved',
      purity: '99.6%',
      spec: 'Ph. Eur / In-House 2026-01',
      storage: 'Store below 25°C in tight container',
      sampleQty: '250 g',
    },
    {
      name: 'Anhydrous Polysaccharide',
      qc: 'QC-00891',
      date: '2026-08-04',
      cat: 'API',
      supplier: 'Global BioReagents Inc',
      batch: 'APS-26-172',
      mfg: 'BioPolymer ChemWorks',
      status: 'Approved',
      purity: '99.8%',
      spec: 'Ph. Eur / In-House 2026-01',
      storage: 'Store below 25°C in tight container',
      sampleQty: '500 g',
    },
    {
      name: 'APS Grade X',
      qc: 'QC-00914',
      date: '2026-08-19',
      cat: 'API',
      supplier: 'Global BioReagents Inc',
      batch: 'APSX-26-003',
      mfg: 'BioPolymer ChemWorks',
      status: 'Approved',
      purity: '99.1%',
      spec: 'Pharma Grade X Spec v2',
      storage: 'Controlled room temperature',
      sampleQty: '100 g',
    },
    {
      name: 'Paracetamol IP',
      qc: 'QC-00140',
      date: '2026-01-15',
      cat: 'API',
      supplier: 'Sun Chemical Synthetics',
      batch: 'PCM-26-042',
      mfg: 'Apex Active Pharma',
      status: 'Approved',
      purity: '99.7%',
      spec: 'IP 2024 / BP 2025',
      storage: 'Protect from light and moisture',
      sampleQty: '500 g',
    },
    {
      name: 'Paracetamol IP',
      qc: 'QC-00512',
      date: '2026-04-10',
      cat: 'API',
      supplier: 'Sun Chemical Synthetics',
      batch: 'PCM-26-105',
      mfg: 'Apex Active Pharma',
      status: 'Approved',
      purity: '99.9%',
      spec: 'IP 2024 / BP 2025',
      storage: 'Protect from light and moisture',
      sampleQty: '500 g',
    },
    {
      name: 'Amoxicillin Trihydrate',
      qc: 'QC-00210',
      date: '2026-02-03',
      cat: 'API',
      supplier: 'BioSynthesis Labs',
      batch: 'AMX-26-011',
      mfg: 'Lupin Chemical Corp',
      status: 'Approved',
      purity: '98.9%',
      spec: 'USP 44 / NF 39',
      storage: 'Store in airtight containers below 20°C',
      sampleQty: '200 g',
    },
    {
      name: 'Metformin Hydrochloride',
      qc: 'QC-00318',
      date: '2026-02-24',
      cat: 'API',
      supplier: 'KDL Chemicals',
      batch: 'MET-26-088',
      mfg: 'Wanbury Lifesciences',
      status: 'Approved',
      purity: '99.5%',
      spec: 'USP / EP standard',
      storage: 'Dry ventilated area',
      sampleQty: '300 g',
    },
    {
      name: 'Ibuprofen BP',
      qc: 'QC-00620',
      date: '2026-05-14',
      cat: 'API',
      supplier: 'Solvent & Fine Chemicals',
      batch: 'IBU-26-033',
      mfg: 'BASF Pharma',
      status: 'Approved',
      purity: '99.8%',
      spec: 'BP 2025',
      storage: 'Room temperature',
      sampleQty: '400 g',
    },
    {
      name: 'Atorvastatin Calcium Trihydrate',
      qc: 'QC-00744',
      date: '2026-06-22',
      cat: 'API',
      supplier: 'Zydus Raw Supply',
      batch: 'ATV-26-092',
      mfg: 'Torrent Active Ingredients',
      status: 'Approved',
      purity: '99.2%',
      spec: 'IP / USP Standard',
      storage: 'Store at 2°C - 8°C (Refrigerated)',
      sampleQty: '150 g',
    },
    {
      name: 'Azithromycin Dihydrate',
      qc: 'QC-00825',
      date: '2026-07-16',
      cat: 'API',
      supplier: 'Alembic Chemicals',
      batch: 'AZI-26-051',
      mfg: 'Alembic Pharmaceuticals',
      status: 'Approved',
      purity: '98.7%',
      spec: 'USP 43',
      storage: 'Airtight container protected from light',
      sampleQty: '200 g',
    },
    {
      name: 'Omeprazole Magnesium',
      qc: 'QC-00966',
      date: '2026-09-02',
      cat: 'API',
      supplier: 'Dr. Reddy Chemical Distribution',
      batch: 'OME-26-118',
      mfg: 'Astra Biotech',
      status: 'Approved',
      purity: '99.3%',
      spec: 'Ph. Eur 10th Ed',
      storage: 'Protect from light and heat',
      sampleQty: '100 g',
    },
  ];

  for (const item of apiItems) {
    records.push({
      source_sheet: 'APIs',
      material_name: item.name,
      material_name_normalized: '',
      qc_number: item.qc,
      date: item.date,
      category: 'API',
      raw_data: {
        'Material Name': item.name,
        'QC Number': item.qc,
        'Date': item.date,
        'Category': item.cat,
        'Supplier': item.supplier,
        'Batch Number': item.batch,
        'Manufacturer': item.mfg,
        'Purity / Assay': item.purity,
        'Pharmacopoeial Spec': item.spec,
        'Storage Condition': item.storage,
        'Sample Quantity': item.sampleQty,
        'QC Status': item.status,
      },
    });
  }

  // ==========================================
  // 2. Excipients
  // ==========================================
  const excipientItems = [
    {
      name: 'Microcrystalline Cellulose (MCC PH-101)',
      qc: 'QC-00108',
      date: '2026-01-08',
      cat: 'Excipient',
      supplier: 'FMC BioPolymer Inc',
      batch: 'MCC-26-004',
      mfg: 'DuPont Nutrition',
      status: 'Approved',
      grade: 'Avicel PH-101 (50 µm)',
      spec: 'USP / NF / EP',
      storage: 'Cool dry place',
      sampleQty: '1000 g',
    },
    {
      name: 'Microcrystalline Cellulose (MCC PH-102)',
      qc: 'QC-00488',
      date: '2026-03-29',
      cat: 'Excipient',
      supplier: 'FMC BioPolymer Inc',
      batch: 'MCC-26-039',
      mfg: 'DuPont Nutrition',
      status: 'Approved',
      grade: 'Avicel PH-102 (100 µm)',
      spec: 'USP / NF / EP',
      storage: 'Cool dry place',
      sampleQty: '1000 g',
    },
    {
      name: 'Polyvinylpyrrolidone (PVP K-30)',
      qc: 'QC-00244',
      date: '2026-02-11',
      cat: 'Excipient',
      supplier: 'BASF Pharma Solutions',
      batch: 'PVP-26-017',
      mfg: 'BASF SE Germany',
      status: 'Approved',
      grade: 'Kollidon 30',
      spec: 'Ph. Eur / USP',
      storage: 'Hygroscopic - Keep tightly sealed',
      sampleQty: '500 g',
    },
    {
      name: 'Magnesium Stearate',
      qc: 'QC-00360',
      date: '2026-03-05',
      cat: 'Excipient',
      supplier: 'Peter Greven Asia',
      batch: 'MGS-26-072',
      mfg: 'Peter Greven GmbH',
      status: 'Approved',
      grade: 'Vegetable Grade / Non-Bovine',
      spec: 'BP / USP-NF',
      storage: 'Well-closed container',
      sampleQty: '300 g',
    },
    {
      name: 'Magnesium Stearate',
      qc: 'QC-00780',
      date: '2026-07-02',
      cat: 'Excipient',
      supplier: 'Peter Greven Asia',
      batch: 'MGS-26-141',
      mfg: 'Peter Greven GmbH',
      status: 'Approved',
      grade: 'Vegetable Grade / Non-Bovine',
      spec: 'BP / USP-NF',
      storage: 'Well-closed container',
      sampleQty: '300 g',
    },
    {
      name: 'Lactose Monohydrate 200 Mesh',
      qc: 'QC-00192',
      date: '2026-01-28',
      cat: 'Excipient',
      supplier: 'DFE Pharma',
      batch: 'LAC-26-081',
      mfg: 'FrieslandCampina',
      status: 'Approved',
      grade: 'Direct Compression & Wet Granulation',
      spec: 'Ph. Eur / NF',
      storage: 'Keep dry below 25°C',
      sampleQty: '1000 g',
    },
    {
      name: 'Hydroxypropyl Methylcellulose (HPMC E15)',
      qc: 'QC-00581',
      date: '2026-04-25',
      cat: 'Excipient',
      supplier: 'Colorcon Inc',
      batch: 'HPMC-26-024',
      mfg: 'Dow Chemical',
      status: 'Approved',
      grade: 'Methocel E15 LV Premium',
      spec: 'USP / EP',
      storage: 'Airtight dry container',
      sampleQty: '400 g',
    },
    {
      name: 'Sodium Starch Glycolate (Type A)',
      qc: 'QC-00677',
      date: '2026-05-30',
      cat: 'Excipient',
      supplier: 'Roquette Freres',
      batch: 'SSG-26-093',
      mfg: 'Roquette France',
      status: 'Approved',
      grade: 'Primojel Superdisintegrant',
      spec: 'Ph. Eur / USP-NF',
      storage: 'Dry conditions',
      sampleQty: '500 g',
    },
    {
      name: 'Colloidal Silicon Dioxide (Aerosil 200)',
      qc: 'QC-00860',
      date: '2026-07-28',
      cat: 'Excipient',
      supplier: 'Evonik Resource Chemicals',
      batch: 'AER-26-019',
      mfg: 'Evonik Industries AG',
      status: 'Approved',
      grade: 'High surface area glidant (200 m²/g)',
      spec: 'USP / NF / EP',
      storage: 'Protect from atmospheric moisture',
      sampleQty: '250 g',
    },
  ];

  for (const item of excipientItems) {
    records.push({
      source_sheet: 'Excipients',
      material_name: item.name,
      material_name_normalized: '',
      qc_number: item.qc,
      date: item.date,
      category: 'Excipient',
      raw_data: {
        'Material Name': item.name,
        'QC Number': item.qc,
        'Date': item.date,
        'Category': item.cat,
        'Supplier': item.supplier,
        'Batch Number': item.batch,
        'Manufacturer': item.mfg,
        'Grade / Physical Form': item.grade,
        'Pharmacopoeial Spec': item.spec,
        'Storage Condition': item.storage,
        'Sample Quantity': item.sampleQty,
        'QC Status': item.status,
      },
    });
  }

  // ==========================================
  // 3. Herbal & Botanical Extracts
  // ==========================================
  const extractItems = [
    {
      name: 'Curcuma Longa Extract 95%',
      qc: 'QC-00230',
      date: '2026-02-08',
      cat: 'Extract',
      supplier: 'Arjuna Natural Extracts',
      batch: 'CUR-26-009',
      mfg: 'Arjuna Natural Ltd',
      status: 'Approved',
      activeContent: 'Curcuminoids >= 95.0% w/w by HPLC',
      spec: 'Ayurvedic Pharmacopoeia / USP Dietary',
      storage: 'Store in airtight amber drums',
      sampleQty: '100 g',
    },
    {
      name: 'Withania Somnifera (Ashwagandha) Extract',
      qc: 'QC-00412',
      date: '2026-03-12',
      cat: 'Extract',
      supplier: 'OmniActive Health Technologies',
      batch: 'ASH-26-033',
      mfg: 'OmniActive Labs',
      status: 'Approved',
      activeContent: 'Withanolides >= 5.0% w/w by HPLC',
      spec: 'API (Ayurvedic) & USP Dietary Spec',
      storage: 'Cool dry warehouse (15-25°C)',
      sampleQty: '150 g',
    },
    {
      name: 'Zingiber Officinale (Ginger) Extract 5%',
      qc: 'QC-00540',
      date: '2026-04-18',
      cat: 'Extract',
      supplier: 'Synthite Industries Ltd',
      batch: 'GIN-26-015',
      mfg: 'Synthite Biotech Division',
      status: 'Approved',
      activeContent: 'Gingerols >= 5.0% w/w',
      spec: 'Ph. Eur Botanical Extract',
      storage: 'Protect from sunlight',
      sampleQty: '100 g',
    },
    {
      name: 'Boswellia Serrata Extract 65%',
      qc: 'QC-00715',
      date: '2026-06-15',
      cat: 'Extract',
      supplier: 'Sabinsa Herbals Corporation',
      batch: 'BOS-26-048',
      mfg: 'Sabinsa Labs',
      status: 'Approved',
      activeContent: 'Boswellic acids >= 65.0%',
      spec: 'In-House Quality Standards 2026',
      storage: 'Room temperature',
      sampleQty: '120 g',
    },
    {
      name: 'Glycyrrhiza Glabra (Licorice) Extract',
      qc: 'QC-00898',
      date: '2026-08-11',
      cat: 'Extract',
      supplier: 'Natural Remedies Botanical Co',
      batch: 'LIC-26-027',
      mfg: 'Natural Remedies Ltd',
      status: 'Approved',
      activeContent: 'Glycyrrhizin >= 20.0%',
      spec: 'Ph. Eur / In-House',
      storage: 'Tightly closed moisture-proof bag',
      sampleQty: '200 g',
    },
  ];

  for (const item of extractItems) {
    records.push({
      source_sheet: 'Extracts',
      material_name: item.name,
      material_name_normalized: '',
      qc_number: item.qc,
      date: item.date,
      category: 'Extract',
      raw_data: {
        'Material Name': item.name,
        'QC Number': item.qc,
        'Date': item.date,
        'Category': item.cat,
        'Supplier': item.supplier,
        'Batch Number': item.batch,
        'Manufacturer': item.mfg,
        'Standardized Marker / Purity': item.activeContent,
        'Quality Specification': item.spec,
        'Storage Condition': item.storage,
        'Sample Quantity': item.sampleQty,
        'QC Status': item.status,
      },
    });
  }

  // ==========================================
  // 4. Packing Materials
  // ==========================================
  const packingItems = [
    {
      name: 'Blister Aluminum Foil 20 Micron (Printed)',
      qc: 'QC-00165',
      date: '2026-01-22',
      cat: 'Packing Material',
      supplier: 'Bilcare Research Ltd',
      batch: 'ALU-26-055',
      mfg: 'Bilcare Packaging Solutions',
      status: 'Approved',
      dims: 'Width 150mm, Thickness 0.020mm',
      spec: 'Heat Seal Lacquer coating >= 5.5 gsm',
      storage: 'Store vertically on pallets',
      sampleQty: '5 meters',
    },
    {
      name: 'PVC Rigid Film 250 Micron (Clear)',
      qc: 'QC-00302',
      date: '2026-02-19',
      cat: 'Packing Material',
      supplier: 'Klöckner Pentaplast',
      batch: 'PVC-26-012',
      mfg: 'Klöckner Pentaplast Group',
      status: 'Approved',
      dims: 'Width 154mm, Thickness 250 µm',
      spec: 'Ph. Eur 3.1.11 / USP 661.1',
      storage: 'Store away from direct thermal sources',
      sampleQty: '10 meters',
    },
    {
      name: 'Amber Glass Bottles 100ml (USP Type III)',
      qc: 'QC-00475',
      date: '2026-03-24',
      cat: 'Packing Material',
      supplier: 'Piramal Glass Containers',
      batch: 'GLS-26-088',
      mfg: 'Piramal Glass Ltd',
      status: 'Approved',
      dims: 'Height 112mm, Neck finish 28mm ROPP',
      spec: 'USP Hydrolytic Resistance Type III',
      storage: 'Dust-free enclosed pallet wrapping',
      sampleQty: '24 bottles',
    },
    {
      name: 'HDPE White Jars 250cc with Induction Wad',
      qc: 'QC-00640',
      date: '2026-05-19',
      cat: 'Packing Material',
      supplier: 'Shree Plastics Molders',
      batch: 'HDP-26-031',
      mfg: 'Shree Industrial Packaging',
      status: 'Approved',
      dims: 'Diameter 62mm, Height 118mm',
      spec: 'US FDA 21 CFR 177.1520',
      storage: 'Enclosed cartons in warehouse',
      sampleQty: '30 containers',
    },
    {
      name: 'Printed Outer Folding Cartons (SBS 350 GSM)',
      qc: 'QC-00810',
      date: '2026-07-09',
      cat: 'Packing Material',
      supplier: 'Parksons Packaging Ltd',
      batch: 'CRN-26-140',
      mfg: 'Parksons Graphics Division',
      status: 'Approved',
      dims: '120 x 45 x 45 mm',
      spec: 'Spot UV varnish, 4 color CMYK printing',
      storage: 'Dry palletized racking',
      sampleQty: '50 cartons',
      tags: ['Carton', 'Packing Material'],
    },
    // USER SPEC EXAMPLE ITEMS: Label + Biotin & Label + High Science
    {
      name: 'Biotin 5000 mcg Label Roll (Self-Adhesive)',
      qc: 'QC-00932',
      date: '2026-09-14',
      cat: 'Packing Material',
      supplier: 'Interprint Pharma Labels',
      batch: 'LBL-26-044',
      mfg: 'Avery Dennison Pharma Div',
      status: 'Approved',
      dims: 'Roll width 48mm, Core 76mm',
      spec: 'Pharma adhesive P60, 80 gsm glossy art paper',
      storage: 'Controlled room temperature (15-25°C)',
      sampleQty: '100 labels',
      tags: ['Label', 'Biotin', 'Printed Material', 'Packing Material'],
      product: 'Biotin 5000 mcg Capsules',
      label: 'Primary Bottle Label',
      brand: 'NutriPharma Health',
      remarks: 'Validated for high-speed automatic rotary labeling machine',
    },
    {
      name: 'High Science Complex Label (30ml Amber Bottle)',
      qc: 'QC-00945',
      date: '2026-09-20',
      cat: 'Packing Material',
      supplier: 'Precision Labels Ltd',
      batch: 'LBL-26-081',
      mfg: 'Precision Graphics',
      status: 'Approved',
      dims: 'Width 65mm x Height 35mm',
      spec: 'Metallic foil hot-stamp, varnish overcoat',
      storage: 'Store away from direct light',
      sampleQty: '150 labels',
      tags: ['Label', 'High Science', 'Primary Label', 'Packing Material'],
      product: 'High Science Bio-Elixir',
      label: 'Bottle Label',
      brand: 'High Science',
      remarks: 'Passed 24h alcohol wipe test and friction test',
    },
    {
      name: 'High Science Outer Carton Label (Secondary Packaging)',
      qc: 'QC-00958',
      date: '2026-09-25',
      cat: 'Packing Material',
      supplier: 'Precision Labels Ltd',
      batch: 'LBL-26-099',
      mfg: 'Precision Graphics',
      status: 'Approved',
      dims: 'Width 85mm x Height 50mm',
      spec: '2D DataMatrix code barcode GS1 compliant',
      storage: 'Dry ventilated area',
      sampleQty: '100 labels',
      tags: ['Label', 'High Science', 'Secondary Packaging', 'Barcode Label'],
      product: 'High Science Bio-Elixir Outer',
      label: 'Carton Seal Label',
      brand: 'High Science',
      remarks: 'Serial numbered tamper evident label roll',
    },
  ];

  for (const item of packingItems) {
    const itemTags = (item as any).tags || [item.cat, 'Packing Material'];
    records.push({
      source: 'excel',
      source_sheet: 'Packing Materials',
      material_name: item.name,
      material_name_normalized: '',
      qc_number: item.qc,
      date: item.date,
      category: 'Packing Material',
      tags: itemTags,
      raw_data: {
        'Material Name': item.name,
        'QC Number': item.qc,
        'Date': item.date,
        'Category': item.cat,
        'Supplier': item.supplier,
        'Batch Number': item.batch,
        'Manufacturer': item.mfg,
        'Dimensions / Physical Spec': item.dims,
        'Standard Test Spec': item.spec,
        'Storage Condition': item.storage,
        'Sample Quantity': item.sampleQty,
        'QC Status': item.status,
        'Tags': itemTags.join(', '),
        ...((item as any).product ? { 'Product': (item as any).product } : {}),
        ...((item as any).label ? { 'Label': (item as any).label } : {}),
        ...((item as any).brand ? { 'Brand': (item as any).brand } : {}),
        ...((item as any).remarks ? { 'Remarks': (item as any).remarks } : {}),
      },
    });
  }

  return records;
}
